name: Publish package to GitHub Packages

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - uses: actions/setup-node@v4
        with:
          node-version: 23
      - name: Install luamin
        run: npm install -g luamin
      - name: Minify some dependencies
        run: cat minify.txt | while read line; do minify.py dependency $line; done
      - name: Build SGS
        run: python packer.py sgs
      - name: Build PSG
        run: python packer.py psg
      - name: Build SSG
        run: python packer.py ssg
      - name: Build TSG
        run: python packer.py tsg
      - name: Build ME portal
        run: python packer.py portal
      - name: Publish assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            out/executables/sgs.lua
            out/executables/install_sgs.lua
            out/executables/psg.lua
            out/executables/install_psg.lua
            out/executables/ssg.lua
            out/executables/install_ssg.lua
            out/executables/tsg.lua
            out/executables/install_tsg.lua
            out/executables/portal.lua
            out/executables/install_portal.lua
