name: Publish package to GitHub Packages

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Build SGS
        run: python packer.py sgs
      - name: Build PSG
        run: python packer.py psg
      - name: Build SSG
        run: python packer.py ssg
      - name: Build TSG
        run: python packer.py tsg
      - name: Build ME portal
        run: python packer.py portal
      - name: Publish assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            out/sgs.lua
            out/install_sgs.lua
            out/psg.lua
            out/install_psg.lua
            out/ssg.lua
            out/install_ssg.lua
            out/tsg.lua
            out/install_tsg.lua
            out/portal.lua
            out/install_portal.lua
